apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: vsnet-social
spec:
  replicas: 5
  template:
    metadata:
      labels:
        role: vsnet-social-server
    spec:
      nodeSelector:
        role: apps
      containers:
      - name: vsnet-social
        image: docker.io/makeshiftsoftware/vsnet-social-dev
        imagePullPolicy: Always
        readinessProbe:
            httpGet:
                path: /readiness
                port: 8080
                scheme: HTTP
            periodSeconds: 5
            timeoutSeconds: 3
        env:
          - name: PORT
            value: "8080"
          - name: REDIS_PUBSUB_SERVICE
            value: social-redis-pubsub:6379
          - name: APP_SECRET
            valueFrom:
              secretKeyRef:
                name: secret
                key: app_secret
          - name: REDIS_PUBSUB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: secret
                key: social_pubsub_redis_password
        ports:
        - containerPort: 8080