version: "3"
services:
  vsnet-social:
    container_name: "vsnet-social"
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - vsnet-social-pubsub
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - PORT=3000
      - APP_SECRET=mysecret
      - REDIS_PUBSUB_SERVICE=redis://vsnet-social-pubsub:6379
  vsnet-social-pubsub:
    container_name: "vsnet-social-pubsub"
    image: redis
    expose:
      - "6379"
    ports:
      - "6379:6379"
