version: "3"
services:
  vsnet-social:
    container_name: "vsnet-social"
    restart: always
    env_file: .env
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "3000"
    ports:
      - "3000:3000"
    depends_on:
      - vs-social-redis-pubsub
  vs-social-redis-pubsub:
    container_name: "vs-social-redis-pubsub"
    image: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"